# AUTOGENERATES the journal b-chapter's tables into journal/tables/*.tex.
# Data sources: the within-K score files (run_withink.py), the test-known files
# (run_withink_test.py) and the primary-grid cells -- regenerate, never retype.
#
#   python experiments/make_journal_tables.py

import json
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np
from scipy import stats as sps

HERE = Path(__file__).resolve().parent
SCORES = HERE / "scores"
OUT = HERE.parent / "journal" / "tables"
OUT.mkdir(parents=True, exist_ok=True)
sys.path.insert(0, str(HERE))

HEADER = "% AUTOGENERATED by experiments/make_journal_tables.py -- do not edit\n"


def pretty(ds):
    lang, _, corpus = ds.rpartition("_")
    genre = {"novels": "nov.", "dracor": "drama", "poetree": "poet."}[corpus]
    return f"{lang.capitalize()} ({genre})"


# --------------------------------------------------------------------------- #
# Table 1: measured per-token b with author-bootstrap CIs, both lengths
# --------------------------------------------------------------------------- #

def author_cross(fn):
    cross = defaultdict(list)
    for line in open(fn, encoding="utf-8"):
        r = json.loads(line)
        if not r["within"]:
            cross[r["known"]].append(r["lambda_G"] / r["n_q"])
    return {a: float(np.mean(v)) for a, v in cross.items() if len(v) >= 4}


def boot_ci(vals, n=2000, seed=0):
    rng = np.random.default_rng(seed)
    v = np.asarray(vals)
    means = [float(np.mean(rng.choice(v, size=len(v), replace=True)))
             for _ in range(n)]
    return float(np.percentile(means, 2.5)), float(np.percentile(means, 97.5))


def tab_b_measured():
    cells = {}
    for L in (2000, 5000):
        for fn in sorted(SCORES.glob(f"*__kn__withink__L{L}.jsonl")):
            ds = fn.name.split("__")[0]
            ac = author_cross(fn)
            if len(ac) >= 8:
                vals = list(ac.values())
                lo, hi = boot_ci(vals)
                cells[(ds, L)] = (float(np.mean(vals)), lo, hi, len(vals))
    datasets = sorted({ds for ds, _ in cells})
    lines = [HEADER, "\\begin{tabular}{lrrrr}", "\\toprule",
             "Dataset & $b_{2000}$ & 95\\,\\% CI & $b_{5000}$ & 95\\,\\% CI \\\\",
             "\\midrule"]
    for ds in datasets:
        row = [pretty(ds)]
        for L in (2000, 5000):
            c = cells.get((ds, L))
            if c:
                row += [f"${c[0]:+.3f}$", f"$[{c[1]:+.3f},\\,{c[2]:+.3f}]$"]
            else:
                row += ["--", "--"]
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_b_measured.tex").write_text("\n".join(lines) + "\n",
                                            encoding="utf-8")
    print(f"tab_b_measured: {len(datasets)} datasets")


# --------------------------------------------------------------------------- #
# Table 2: within-K -> H_d location correlations per dataset, both lengths
# --------------------------------------------------------------------------- #

def author_stats(fn):
    within, cross = defaultdict(list), defaultdict(list)
    for line in open(fn, encoding="utf-8"):
        r = json.loads(line)
        (within if r["within"] else cross)[r["known"]].append(
            r["lambda_G"] / r["n_q"])
    return {a: (float(np.mean(within[a])), float(np.mean(cross[a])))
            for a in within if len(within[a]) >= 6 and len(cross.get(a, [])) >= 6}


def tab_withink():
    rows = {}
    meds = {}
    for L in (2000, 5000):
        rs = []
        for fn in sorted(SCORES.glob(f"*__kn__withink__L{L}.jsonl")):
            ds = fn.name.split("__")[0]
            st = author_stats(fn)
            if len(st) < 8:
                continue
            wm = [v[0] for v in st.values()]
            cm = [v[1] for v in st.values()]
            r = float(sps.spearmanr(wm, cm).statistic)
            rows.setdefault(ds, {})[L] = (r, len(st))
            rs.append(r)
        meds[L] = (float(np.median(rs)), sum(1 for r in rs if r < 0), len(rs))
    lines = [HEADER, "\\begin{tabular}{lrrrr}", "\\toprule",
             "Dataset & $n_{2000}$ & $\\rho_{2000}$ & $n_{5000}$ & "
             "$\\rho_{5000}$ \\\\", "\\midrule"]
    for ds in sorted(rows):
        row = [pretty(ds)]
        for L in (2000, 5000):
            c = rows[ds].get(L)
            row += ([f"{c[1]}", f"${c[0]:+.2f}$"] if c else ["--", "--"])
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\midrule",
              f"Median & & ${meds[2000][0]:+.2f}$ "
              f"({meds[2000][1]}/{meds[2000][2]} neg.) & & "
              f"${meds[5000][0]:+.2f}$ ({meds[5000][1]}/{meds[5000][2]} neg.) \\\\",
              "\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_withink.tex").write_text("\n".join(lines) + "\n",
                                         encoding="utf-8")
    print(f"tab_withink: {len(rows)} datasets; medians "
          f"{meds[2000][0]:+.2f}/{meds[5000][0]:+.2f}")


# --------------------------------------------------------------------------- #
# Table 3: the decisive matched-L rescue test (imports analyze_decisive)
# --------------------------------------------------------------------------- #

def tab_decisive():
    import io
    import contextlib
    import analyze_decisive as AD
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        AD.main()
    body = [l for l in buf.getvalue().splitlines()
            if l and not l.startswith(("dataset", "L="))]
    lines = [HEADER, "\\begin{tabular}{lrrrrrrr}", "\\toprule",
             "Dataset & $L$ & $n$ & AUC raw/$\\hat b$ & "
             "$C_{\\mathrm{llr}}$ raw & $\\hat b$ & oracle & pooled \\\\",
             "\\midrule"]
    for l in body:
        p = l.split()
        if len(p) < 9:
            continue
        ds, L, n, _cov, auc, craw, cb, co, cp = p[:9]
        lines.append(f"{pretty(ds)} & {L} & {n} & {auc} & {craw} & {cb} & "
                     f"{co} & {cp} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_decisive.tex").write_text("\n".join(lines) + "\n",
                                          encoding="utf-8")
    print(f"tab_decisive: {sum(1 for l in lines if l.endswith(chr(92)*2))} rows")


# --------------------------------------------------------------------------- #
# Table 4: the symmetrised estimator / mismatch-meter arms
# --------------------------------------------------------------------------- #

def tab_symmeter():
    arms = []
    for fn in sorted(SCORES.glob("*__symref-*__L2000.jsonl")):
        rows = [json.loads(l) for l in open(fn, encoding="utf-8")]
        if not rows:
            continue
        ds, refds = fn.name.replace("__L2000.jsonl", "").split("__symref-")
        c = np.array([r["lambda_G"] / r["n_q"] for r in rows if not r["within"]])
        se = float(c.std(ddof=1) / np.sqrt(len(c)))
        arms.append((ds == refds, pretty(ds), pretty(refds), len(c),
                     float(c.mean()), 1.96 * se))
    arms.sort(key=lambda t: (not t[0], t[4]))
    lines = [HEADER, "\\begin{tabular}{llrrr}", "\\toprule",
             "Known authors & Reference corpus & $n$ & $b_{\\mathrm{sym}}$ & "
             "95\\,\\% CI \\\\", "\\midrule"]
    seen_mm = False
    for matched, ds, refds, n, m, ci in arms:
        if not matched and not seen_mm:
            lines.append("\\midrule")
            seen_mm = True
        lines.append(f"{ds} & {refds if not matched else '(same)'} & {n} & "
                     f"${m:+.4f}$ & $\\pm{ci:.4f}$ \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_symmeter.tex").write_text("\n".join(lines) + "\n",
                                          encoding="utf-8")
    print(f"tab_symmeter: {len(arms)} arms")


# --------------------------------------------------------------------------- #
# Table 5: tempered control + matched-arm studentisation (Cllr per variant)
# --------------------------------------------------------------------------- #

def tab_tempered():
    from lambdag import cllr
    lines = [HEADER, "\\begin{tabular}{lrrrr}", "\\toprule",
             "Dataset & $\\lambda/\\sqrt{N}$ & clipped & rescaled & "
             "studentised \\\\", "\\midrule"]
    meds = {k: [] for k in range(4)}
    for fn in sorted(SCORES.glob("*__symref-*__L2000.jsonl")):
        ds, refds = fn.name.replace("__L2000.jsonl", "").split("__symref-")
        if ds != refds:
            continue
        rows = [json.loads(l) for l in open(fn, encoding="utf-8")]
        if not rows:
            continue
        y = np.array([r["within"] for r in rows])
        sq = np.array([r["lambda_G"] / np.sqrt(r["n_q"]) for r in rows])
        st = np.array([float(np.mean(r["lam_j"]) /
                             (np.std(r["lam_j"], ddof=1) + 1e-9)) for r in rows])
        variants = [sq, np.clip(sq, -4, 4),
                    sq * (st.std(ddof=1) / (sq.std(ddof=1) + 1e-9)), st]
        cs = [float(cllr(s[y == 1], s[y == 0])) for s in variants]
        for i, c in enumerate(cs):
            meds[i].append(c)
        lines.append(f"{pretty(ds)} & " + " & ".join(f"{c:.2f}" for c in cs)
                     + " \\\\")
    lines += ["\\midrule", "Median & " +
              " & ".join(f"{np.median(v):.2f}" for v in meds.values()) + " \\\\",
              "\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_tempered.tex").write_text("\n".join(lines) + "\n",
                                          encoding="utf-8")
    print(f"tab_tempered: {len(meds[0])} matched arms")


# --------------------------------------------------------------------------- #
# Table 6: real-case cohort studentisation (L = 1200)
# --------------------------------------------------------------------------- #

def tab_routeb_real():
    from lambdag import cllr, cllr_min as cmin
    from sklearn.metrics import roc_auc_score
    lines = [HEADER, "\\begin{tabular}{lrrrrrr}", "\\toprule",
             "Dataset & $n$ & AUC plain/stud. & $C_{\\mathrm{llr}}$ plain & "
             "cohort mean & studentised & floor \\\\", "\\midrule"]
    meds = []
    for fn in sorted(SCORES.glob("*__routebreal__L1200.jsonl")):
        ds = fn.name.split("__")[0]
        recs = [json.loads(l) for l in open(fn, encoding="utf-8")]
        gfn = SCORES / f"{ds}__kn__sent__L1200.jsonl"
        grid = {r["id"]: r for r in
                (json.loads(l) for l in open(gfn, encoding="utf-8"))}
        y, g, ss, st = [], [], [], []
        for r in recs:
            if r["id"] not in grid:
                continue
            lj = np.asarray(r["lam_j"], dtype=float)
            y.append(r["label"]); g.append(grid[r["id"]]["sqrt"])
            ss.append(float(np.mean(lj)) / np.sqrt(r["n_q"]))
            st.append(float(np.mean(lj) / (np.std(lj, ddof=1) + 1e-9)))
        y = np.array(y)
        g, ss, st = np.array(g), np.array(ss), np.array(st)
        cg = float(cllr(g[y == 1], g[y == 0]))
        cs = float(cllr(ss[y == 1], ss[y == 0]))
        ct = float(cllr(st[y == 1], st[y == 0]))
        meds.append((cg, ct))
        lines.append(f"{pretty(ds)} & {len(y)} & "
                     f"{roc_auc_score(y, g):.3f}/{roc_auc_score(y, st):.3f} & "
                     f"{cg:.2f} & {cs:.2f} & \\textbf{{{ct:.2f}}} & "
                     f"{cmin(st[y == 1], st[y == 0]):.2f} \\\\")
    lines += ["\\midrule",
              f"Median & & & {np.median([m[0] for m in meds]):.2f} & & "
              f"\\textbf{{{np.median([m[1] for m in meds]):.2f}}} & \\\\",
              "\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_routeb_real.tex").write_text("\n".join(lines) + "\n",
                                             encoding="utf-8")
    print(f"tab_routeb_real: {len(meds)} datasets")


# --------------------------------------------------------------------------- #
# Figure: dataset-level scatter (median within-fit vs median H_d location)
# --------------------------------------------------------------------------- #

def fig_scatter():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from scipy import stats as sps
    fig, axes = plt.subplots(1, 2, figsize=(9.2, 4.0), sharey=False)
    for ax, L in zip(axes, (2000, 5000)):
        xs, ys = [], []
        for fn in sorted(SCORES.glob(f"*__kn__withink__L{L}.jsonl")):
            st = author_stats(fn)
            if len(st) >= 8:
                xs.append(float(np.median([v[0] for v in st.values()])))
                ys.append(float(np.median([v[1] for v in st.values()])))
        ax.scatter(xs, ys, s=42, color="#2a78d6", alpha=0.85,
                   edgecolor="white", linewidth=1.2)
        rho = sps.spearmanr(xs, ys).statistic
        ax.set_title(f"$L={L}$  ({len(xs)} datasets, "
                     f"$\\rho={rho:+.2f}$)", fontsize=10)
        ax.set_xlabel("median within-author self-fit (per token)")
        ax.grid(True, color="#e6e4e0", linewidth=0.8)
        ax.set_axisbelow(True)
        for s in ("top", "right"):
            ax.spines[s].set_visible(False)
    axes[0].set_ylabel("median $H_d$ location (per token)")
    fig.tight_layout()
    fig.savefig(OUT.parent / "figures" / "fig_withink_scatter.pdf")
    print("fig_withink_scatter.pdf")


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    tab_b_measured()
    tab_withink()
    tab_decisive()
    tab_symmeter()
    tab_tempered()
    tab_routeb_real()
    fig_scatter()
