# AUTOGENERATES the journal b-chapter's tables into journal/tables/*.tex.
# Data sources: the within-K score files (run_withink.py), the test-known files
# (run_withink_test.py) and the primary-grid cells -- regenerate, never retype.
#
#   python experiments/make_journal_tables.py

import json
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np
from scipy import stats as sps

HERE = Path(__file__).resolve().parent
SCORES = HERE / "scores"
OUT = HERE.parent / "journal" / "tables"
OUT.mkdir(parents=True, exist_ok=True)
sys.path.insert(0, str(HERE))

HEADER = "% AUTOGENERATED by experiments/make_journal_tables.py -- do not edit\n"


def pretty(ds):
    lang, _, corpus = ds.rpartition("_")
    genre = {"novels": "nov.", "dracor": "drama", "poetree": "poet."}[corpus]
    return f"{lang.capitalize()} ({genre})"


# --------------------------------------------------------------------------- #
# Table 1: measured per-token b with author-bootstrap CIs, both lengths
# --------------------------------------------------------------------------- #

def author_cross(fn):
    cross = defaultdict(list)
    for line in open(fn, encoding="utf-8"):
        r = json.loads(line)
        if not r["within"]:
            cross[r["known"]].append(r["lambda_G"] / r["n_q"])
    return {a: float(np.mean(v)) for a, v in cross.items() if len(v) >= 4}


def boot_ci(vals, n=2000, seed=0):
    rng = np.random.default_rng(seed)
    v = np.asarray(vals)
    means = [float(np.mean(rng.choice(v, size=len(v), replace=True)))
             for _ in range(n)]
    return float(np.percentile(means, 2.5)), float(np.percentile(means, 97.5))


def tab_b_measured():
    cells = {}
    for L in (2000, 5000):
        for fn in sorted(SCORES.glob(f"*__kn__withink__L{L}.jsonl")):
            ds = fn.name.split("__")[0]
            ac = author_cross(fn)
            if len(ac) >= 8:
                vals = list(ac.values())
                lo, hi = boot_ci(vals)
                cells[(ds, L)] = (float(np.mean(vals)), lo, hi, len(vals))
    datasets = sorted({ds for ds, _ in cells})
    lines = [HEADER, "\\begin{tabular}{lrrrr}", "\\toprule",
             "Dataset & $b_{2000}$ & 95\\,\\% CI & $b_{5000}$ & 95\\,\\% CI \\\\",
             "\\midrule"]
    for ds in datasets:
        row = [pretty(ds)]
        for L in (2000, 5000):
            c = cells.get((ds, L))
            if c:
                row += [f"${c[0]:+.3f}$", f"$[{c[1]:+.3f},\\,{c[2]:+.3f}]$"]
            else:
                row += ["--", "--"]
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_b_measured.tex").write_text("\n".join(lines) + "\n",
                                            encoding="utf-8")
    print(f"tab_b_measured: {len(datasets)} datasets")


# --------------------------------------------------------------------------- #
# Table 2: within-K -> H_d location correlations per dataset, both lengths
# --------------------------------------------------------------------------- #

def author_stats(fn):
    within, cross = defaultdict(list), defaultdict(list)
    for line in open(fn, encoding="utf-8"):
        r = json.loads(line)
        (within if r["within"] else cross)[r["known"]].append(
            r["lambda_G"] / r["n_q"])
    return {a: (float(np.mean(within[a])), float(np.mean(cross[a])))
            for a in within if len(within[a]) >= 6 and len(cross.get(a, [])) >= 6}


def tab_withink():
    rows = {}
    meds = {}
    for L in (2000, 5000):
        rs = []
        for fn in sorted(SCORES.glob(f"*__kn__withink__L{L}.jsonl")):
            ds = fn.name.split("__")[0]
            st = author_stats(fn)
            if len(st) < 8:
                continue
            wm = [v[0] for v in st.values()]
            cm = [v[1] for v in st.values()]
            r = float(sps.spearmanr(wm, cm).statistic)
            rows.setdefault(ds, {})[L] = (r, len(st))
            rs.append(r)
        meds[L] = (float(np.median(rs)), sum(1 for r in rs if r < 0), len(rs))
    lines = [HEADER, "\\begin{tabular}{lrrrr}", "\\toprule",
             "Dataset & $n_{2000}$ & $\\rho_{2000}$ & $n_{5000}$ & "
             "$\\rho_{5000}$ \\\\", "\\midrule"]
    for ds in sorted(rows):
        row = [pretty(ds)]
        for L in (2000, 5000):
            c = rows[ds].get(L)
            row += ([f"{c[1]}", f"${c[0]:+.2f}$"] if c else ["--", "--"])
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\midrule",
              f"Median & & ${meds[2000][0]:+.2f}$ "
              f"({meds[2000][1]}/{meds[2000][2]} neg.) & & "
              f"${meds[5000][0]:+.2f}$ ({meds[5000][1]}/{meds[5000][2]} neg.) \\\\",
              "\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_withink.tex").write_text("\n".join(lines) + "\n",
                                         encoding="utf-8")
    print(f"tab_withink: {len(rows)} datasets; medians "
          f"{meds[2000][0]:+.2f}/{meds[5000][0]:+.2f}")


# --------------------------------------------------------------------------- #
# Table 3: the decisive matched-L rescue test (imports analyze_decisive)
# --------------------------------------------------------------------------- #

def tab_decisive():
    import io
    import contextlib
    import analyze_decisive as AD
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        AD.main()
    body = [l for l in buf.getvalue().splitlines()
            if l and not l.startswith(("dataset", "L="))]
    lines = [HEADER, "\\begin{tabular}{lrrrrrrr}", "\\toprule",
             "Dataset & $L$ & $n$ & AUC raw/$\\hat b$ & "
             "$C_{\\mathrm{llr}}$ raw & $\\hat b$ & oracle & pooled \\\\",
             "\\midrule"]
    for l in body:
        p = l.split()
        if len(p) < 9:
            continue
        ds, L, n, _cov, auc, craw, cb, co, cp = p[:9]
        lines.append(f"{pretty(ds)} & {L} & {n} & {auc} & {craw} & {cb} & "
                     f"{co} & {cp} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_decisive.tex").write_text("\n".join(lines) + "\n",
                                          encoding="utf-8")
    print(f"tab_decisive: {sum(1 for l in lines if l.endswith(chr(92)*2))} rows")


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    tab_b_measured()
    tab_withink()
    tab_decisive()
