# AUTOGENERATES the journal b-chapter's tables into journal/tables/*.tex.
# Data sources: the within-K score files (run_withink.py), the test-known files
# (run_withink_test.py) and the primary-grid cells -- regenerate, never retype.
#
#   python experiments/make_journal_tables.py

import json
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np
from scipy import stats as sps

HERE = Path(__file__).resolve().parent
SCORES = HERE / "scores"
OUT = HERE.parent / "journal" / "tables"
OUT.mkdir(parents=True, exist_ok=True)
sys.path.insert(0, str(HERE))

HEADER = "% AUTOGENERATED by experiments/make_journal_tables.py -- do not edit\n"


def pretty(ds):
    lang, _, corpus = ds.rpartition("_")
    genre = {"novels": "nov.", "dracor": "drama", "poetree": "poet."}[corpus]
    return f"{lang.capitalize()} ({genre})"


# --------------------------------------------------------------------------- #
# Table 1: measured per-token b with author-bootstrap CIs, both lengths
# --------------------------------------------------------------------------- #

def author_cross(fn):
    cross = defaultdict(list)
    for line in open(fn, encoding="utf-8"):
        r = json.loads(line)
        if not r["within"]:
            cross[r["known"]].append(r["lambda_G"] / r["n_q"])
    return {a: float(np.mean(v)) for a, v in cross.items() if len(v) >= 4}


def boot_ci(vals, n=2000, seed=0):
    rng = np.random.default_rng(seed)
    v = np.asarray(vals)
    means = [float(np.mean(rng.choice(v, size=len(v), replace=True)))
             for _ in range(n)]
    return float(np.percentile(means, 2.5)), float(np.percentile(means, 97.5))


def tab_b_measured():
    cells = {}
    for L in (2000, 5000):
        for fn in sorted(SCORES.glob(f"*__kn__withink__L{L}.jsonl")):
            ds = fn.name.split("__")[0]
            ac = author_cross(fn)
            if len(ac) >= 8:
                vals = list(ac.values())
                lo, hi = boot_ci(vals)
                cells[(ds, L)] = (float(np.mean(vals)), lo, hi, len(vals))
    datasets = sorted({ds for ds, _ in cells})
    lines = [HEADER, "\\begin{tabular}{lrrrr}", "\\toprule",
             "Dataset & $b_{2000}$ & 95\\,\\% CI & $b_{5000}$ & 95\\,\\% CI \\\\",
             "\\midrule"]
    for ds in datasets:
        row = [pretty(ds)]
        for L in (2000, 5000):
            c = cells.get((ds, L))
            if c:
                row += [f"${c[0]:+.3f}$", f"$[{c[1]:+.3f},\\,{c[2]:+.3f}]$"]
            else:
                row += ["--", "--"]
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_b_measured.tex").write_text("\n".join(lines) + "\n",
                                            encoding="utf-8")
    print(f"tab_b_measured: {len(datasets)} datasets")


# --------------------------------------------------------------------------- #
# Table 2: within-K -> H_d location correlations per dataset, both lengths
# --------------------------------------------------------------------------- #

def author_stats(fn):
    within, cross = defaultdict(list), defaultdict(list)
    for line in open(fn, encoding="utf-8"):
        r = json.loads(line)
        (within if r["within"] else cross)[r["known"]].append(
            r["lambda_G"] / r["n_q"])
    return {a: (float(np.mean(within[a])), float(np.mean(cross[a])))
            for a in within if len(within[a]) >= 6 and len(cross.get(a, [])) >= 6}


def tab_withink():
    rows = {}
    meds = {}
    for L in (2000, 5000):
        rs = []
        for fn in sorted(SCORES.glob(f"*__kn__withink__L{L}.jsonl")):
            ds = fn.name.split("__")[0]
            st = author_stats(fn)
            if len(st) < 8:
                continue
            wm = [v[0] for v in st.values()]
            cm = [v[1] for v in st.values()]
            r = float(sps.spearmanr(wm, cm).statistic)
            rows.setdefault(ds, {})[L] = (r, len(st))
            rs.append(r)
        meds[L] = (float(np.median(rs)), sum(1 for r in rs if r < 0), len(rs))
    lines = [HEADER, "\\begin{tabular}{lrrrr}", "\\toprule",
             "Dataset & $n_{2000}$ & $\\rho_{2000}$ & $n_{5000}$ & "
             "$\\rho_{5000}$ \\\\", "\\midrule"]
    for ds in sorted(rows):
        row = [pretty(ds)]
        for L in (2000, 5000):
            c = rows[ds].get(L)
            row += ([f"{c[1]}", f"${c[0]:+.2f}$"] if c else ["--", "--"])
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\midrule",
              f"Median & & ${meds[2000][0]:+.2f}$ "
              f"({meds[2000][1]}/{meds[2000][2]} neg.) & & "
              f"${meds[5000][0]:+.2f}$ ({meds[5000][1]}/{meds[5000][2]} neg.) \\\\",
              "\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_withink.tex").write_text("\n".join(lines) + "\n",
                                         encoding="utf-8")
    print(f"tab_withink: {len(rows)} datasets; medians "
          f"{meds[2000][0]:+.2f}/{meds[5000][0]:+.2f}")


# --------------------------------------------------------------------------- #
# Table 3: the decisive matched-L rescue test (imports analyze_decisive)
# --------------------------------------------------------------------------- #

def tab_decisive():
    import io
    import contextlib
    import analyze_decisive as AD
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        AD.main()
    body = [l for l in buf.getvalue().splitlines()
            if l and not l.startswith(("dataset", "L="))]
    lines = [HEADER, "\\begin{tabular}{lrrrrrrr}", "\\toprule",
             "Dataset & $L$ & $n$ & AUC raw/$\\hat b$ & "
             "$C_{\\mathrm{llr}}$ raw & $\\hat b$ & oracle & pooled \\\\",
             "\\midrule"]
    for l in body:
        p = l.split()
        if len(p) < 9:
            continue
        ds, L, n, _cov, auc, craw, cb, co, cp = p[:9]
        lines.append(f"{pretty(ds)} & {L} & {n} & {auc} & {craw} & {cb} & "
                     f"{co} & {cp} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_decisive.tex").write_text("\n".join(lines) + "\n",
                                          encoding="utf-8")
    print(f"tab_decisive: {sum(1 for l in lines if l.endswith(chr(92)*2))} rows")


# --------------------------------------------------------------------------- #
# Table 4: the symmetrised estimator / mismatch-meter arms
# --------------------------------------------------------------------------- #

def tab_symmeter():
    arms = []
    for fn in sorted(SCORES.glob("*__symref-*__L2000.jsonl")):
        rows = [json.loads(l) for l in open(fn, encoding="utf-8")]
        if not rows:
            continue
        ds, refds = fn.name.replace("__L2000.jsonl", "").split("__symref-")
        c = np.array([r["lambda_G"] / r["n_q"] for r in rows if not r["within"]])
        se = float(c.std(ddof=1) / np.sqrt(len(c)))
        arms.append((ds == refds, pretty(ds), pretty(refds), len(c),
                     float(c.mean()), 1.96 * se))
    arms.sort(key=lambda t: (not t[0], t[4]))
    lines = [HEADER, "\\begin{tabular}{llrrr}", "\\toprule",
             "Known authors & Reference corpus & $n$ & $b_{\\mathrm{sym}}$ & "
             "95\\,\\% CI \\\\", "\\midrule"]
    seen_mm = False
    for matched, ds, refds, n, m, ci in arms:
        if not matched and not seen_mm:
            lines.append("\\midrule")
            seen_mm = True
        lines.append(f"{ds} & {refds if not matched else '(same)'} & {n} & "
                     f"${m:+.4f}$ & $\\pm{ci:.4f}$ \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_symmeter.tex").write_text("\n".join(lines) + "\n",
                                          encoding="utf-8")
    print(f"tab_symmeter: {len(arms)} arms")


# --------------------------------------------------------------------------- #
# Table 5: tempered control + matched-arm studentisation (Cllr per variant)
# --------------------------------------------------------------------------- #

def tab_tempered():
    from lambdag import cllr
    lines = [HEADER, "\\begin{tabular}{lrrrr}", "\\toprule",
             "Dataset & $\\lambda/\\sqrt{N}$ & clipped & rescaled & "
             "studentised \\\\", "\\midrule"]
    meds = {k: [] for k in range(4)}
    for fn in sorted(SCORES.glob("*__symref-*__L2000.jsonl")):
        ds, refds = fn.name.replace("__L2000.jsonl", "").split("__symref-")
        if ds != refds:
            continue
        rows = [json.loads(l) for l in open(fn, encoding="utf-8")]
        if not rows:
            continue
        y = np.array([r["within"] for r in rows])
        sq = np.array([r["lambda_G"] / np.sqrt(r["n_q"]) for r in rows])
        st = np.array([float(np.mean(r["lam_j"]) /
                             (np.std(r["lam_j"], ddof=1) + 1e-9)) for r in rows])
        variants = [sq, np.clip(sq, -4, 4),
                    sq * (st.std(ddof=1) / (sq.std(ddof=1) + 1e-9)), st]
        cs = [float(cllr(s[y == 1], s[y == 0])) for s in variants]
        for i, c in enumerate(cs):
            meds[i].append(c)
        lines.append(f"{pretty(ds)} & " + " & ".join(f"{c:.2f}" for c in cs)
                     + " \\\\")
    lines += ["\\midrule", "Median & " +
              " & ".join(f"{np.median(v):.2f}" for v in meds.values()) + " \\\\",
              "\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_tempered.tex").write_text("\n".join(lines) + "\n",
                                          encoding="utf-8")
    print(f"tab_tempered: {len(meds[0])} matched arms")


# --------------------------------------------------------------------------- #
# Table 6: real-case cohort studentisation (L = 1200)
# --------------------------------------------------------------------------- #

def tab_routeb_real():
    from lambdag import cllr, cllr_min as cmin
    from sklearn.metrics import roc_auc_score
    lines = [HEADER, "\\begin{tabular}{lrrrrrr}", "\\toprule",
             "Dataset & $n$ & AUC plain/stud. & $C_{\\mathrm{llr}}$ plain & "
             "cohort mean & studentised & floor \\\\", "\\midrule"]
    meds = []
    for fn in sorted(SCORES.glob("*__routebreal__L1200.jsonl")):
        ds = fn.name.split("__")[0]
        recs = [json.loads(l) for l in open(fn, encoding="utf-8")]
        gfn = SCORES / f"{ds}__kn__sent__L1200.jsonl"
        grid = {r["id"]: r for r in
                (json.loads(l) for l in open(gfn, encoding="utf-8"))}
        y, g, ss, st = [], [], [], []
        for r in recs:
            if r["id"] not in grid:
                continue
            lj = np.asarray(r["lam_j"], dtype=float)
            y.append(r["label"]); g.append(grid[r["id"]]["sqrt"])
            ss.append(float(np.mean(lj)) / np.sqrt(r["n_q"]))
            st.append(float(np.mean(lj) / (np.std(lj, ddof=1) + 1e-9)))
        y = np.array(y)
        g, ss, st = np.array(g), np.array(ss), np.array(st)
        cg = float(cllr(g[y == 1], g[y == 0]))
        cs = float(cllr(ss[y == 1], ss[y == 0]))
        ct = float(cllr(st[y == 1], st[y == 0]))
        meds.append((cg, ct))
        lines.append(f"{pretty(ds)} & {len(y)} & "
                     f"{roc_auc_score(y, g):.3f}/{roc_auc_score(y, st):.3f} & "
                     f"{cg:.2f} & {cs:.2f} & \\textbf{{{ct:.2f}}} & "
                     f"{cmin(st[y == 1], st[y == 0]):.2f} \\\\")
    lines += ["\\midrule",
              f"Median & & & {np.median([m[0] for m in meds]):.2f} & & "
              f"\\textbf{{{np.median([m[1] for m in meds]):.2f}}} & \\\\",
              "\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_routeb_real.tex").write_text("\n".join(lines) + "\n",
                                             encoding="utf-8")
    print(f"tab_routeb_real: {len(meds)} datasets")


# --------------------------------------------------------------------------- #
# Figure: dataset-level scatter (median within-fit vs median H_d location)
# --------------------------------------------------------------------------- #

def fig_scatter():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from scipy import stats as sps
    fig, axes = plt.subplots(1, 2, figsize=(9.2, 4.0), sharey=False)
    for ax, L in zip(axes, (2000, 5000)):
        xs, ys = [], []
        for fn in sorted(SCORES.glob(f"*__kn__withink__L{L}.jsonl")):
            st = author_stats(fn)
            if len(st) >= 8:
                xs.append(float(np.median([v[0] for v in st.values()])))
                ys.append(float(np.median([v[1] for v in st.values()])))
        ax.scatter(xs, ys, s=42, color="#2a78d6", alpha=0.85,
                   edgecolor="white", linewidth=1.2)
        rho = sps.spearmanr(xs, ys).statistic
        ax.set_title(f"$L={L}$  ({len(xs)} datasets, "
                     f"$\\rho={rho:+.2f}$)", fontsize=10)
        ax.set_xlabel("median within-author self-fit (per token)")
        ax.grid(True, color="#e6e4e0", linewidth=0.8)
        ax.set_axisbelow(True)
        for s in ("top", "right"):
            ax.spines[s].set_visible(False)
    axes[0].set_ylabel("median $H_d$ location (per token)")
    fig.tight_layout()
    fig.savefig(OUT.parent / "figures" / "fig_withink_scatter.pdf")
    print("fig_withink_scatter.pdf")


# --------------------------------------------------------------------------- #
# Table 7: engine baseline medians (KN / HPY / PPMd x symmetric lengths)
# --------------------------------------------------------------------------- #

ENG_LANGS = ["czech", "english", "french", "hungarian", "latvian",
             "lithuanian", "polish", "ukrainian"]


def _cell_metrics(ds, eng, L):
    from lambdag import cllr, cllr_min
    from sklearn.metrics import roc_auc_score
    fn = SCORES / f"{ds}__{eng}__sent__L{L}.jsonl"
    if not fn.exists():
        return None
    recs = [json.loads(l) for l in open(fn, encoding="utf-8")]
    if not recs:
        return None
    y = np.array([r["label"] for r in recs])
    if len(set(y.tolist())) < 2:
        return None
    lam = np.array([r["lambda_G"] for r in recs])
    s = np.array([r["sqrt"] for r in recs])
    return (float(roc_auc_score(y, lam)),
            float(cllr(s[y == 1], s[y == 0])),
            float(cllr_min(s[y == 1], s[y == 0])))


def tab_engines():
    engines = [("kn", "Kneser--Ney"), ("hpy", "HPY (defaults)"),
               ("ppmd_static", "PPMd static"), ("ppmd_sent", "PPMd adaptive")]
    lengths = [0, 1200, 600, 300, 150]
    lines = [HEADER, "\\begin{tabular}{lrrrrr}", "\\toprule",
             "Engine & full & 1200 & 600 & 300 & 150 \\\\", "\\midrule"]
    for metric, fmt in (("AUC", "{:.3f}"), ("Cllr", "{:.2f}")):
        lines.append(f"\\multicolumn{{6}}{{l}}{{\\emph{{median "
                     f"{'AUC (raw score)' if metric == 'AUC' else 'C llr (sqrt-corrected)'}}}}} \\\\")
        for eng, name in engines:
            row = [name]
            for L in lengths:
                vals = [m for ds in ENG_LANGS
                        if (m := _cell_metrics(f"{ds}_novels", eng, L))]
                idx = 0 if metric == "AUC" else 1
                row.append(fmt.format(float(np.median([v[idx] for v in vals])))
                           if vals else "--")
            lines.append(" & ".join(row) + " \\\\")
        if metric == "AUC":
            lines.append("\\midrule")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_engines.tex").write_text("\n".join(lines) + "\n",
                                         encoding="utf-8")
    print("tab_engines written")


# --------------------------------------------------------------------------- #
# Table 8: HPY parameter sweep (medians over lt/hu/en)
# --------------------------------------------------------------------------- #

def tab_hpy():
    variants = [
        ("kn", "Kneser--Ney (anchor)"),
        ("hpy_t0_min", "$\\theta{=}0$, minimal ($\\equiv$ KN)"),
        ("hpy_t1_min", "$\\theta{=}1$, minimal"),
        ("hpy_t5_min", "$\\theta{=}5$, minimal"),
        ("hpy_t10_min", "$\\theta{=}10$, minimal"),
        ("hpy_t0_exp", "$\\theta{=}0$, expected"),
        ("hpy_t1_exp", "$\\theta{=}1$, expected"),
        ("hpy_t10_exp", "$\\theta{=}10$, expected"),
        ("hpy_t0_min_d50", "$d{=}0.5$, minimal"),
        ("hpy_t0_min_d90", "$d{=}0.9$, minimal"),
    ]
    ds3 = ["lithuanian_novels", "hungarian_novels", "english_novels"]
    lines = [HEADER, "\\begin{tabular}{lrrrr}", "\\toprule",
             " & \\multicolumn{2}{c}{full} & \\multicolumn{2}{c}{$L=600$} \\\\",
             "Variant & AUC & $C_{\\mathrm{llr}}$ & AUC & $C_{\\mathrm{llr}}$ \\\\",
             "\\midrule"]
    for eng, name in variants:
        row = [name]
        for L in (0, 600):
            vals = [m for ds in ds3 if (m := _cell_metrics(ds, eng, L))]
            if vals:
                row.append(f"{np.median([v[0] for v in vals]):.3f}")
                row.append(f"{np.median([v[1] for v in vals]):.2f}")
            else:
                row += ["--", "--"]
        lines.append(" & ".join(row) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_hpy.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("tab_hpy written")


# --------------------------------------------------------------------------- #
# Table: cross-lingual transfer, four universal alphabets x three window sizes
# (parsed from the xling_pilot.py logs -- regenerate, never retype)
# --------------------------------------------------------------------------- #

XLING_LOGS = ["xling_pilot.log", "xling_pilot_cats.log",
              "xling_pilot_catsrank1000.log", "xling_pilot_w500.log",
              "xling_pilot_w250.log"]
XLING_MODES = ["tags", "ranks", "cats", "catsrank"]
XLING_LANGS = ["german", "english", "french", "polish", "czech", "hungarian"]


def parse_xling():
    """(mode, W, lang) -> LOLO-xgb AUC, from the pilot logs."""
    cells, mode, w = {}, None, None
    for log in XLING_LOGS:
        for line in open(HERE / log, encoding="utf-8"):
            if line.startswith("=== mode="):
                mode = line.split("mode=")[1].split()[0]
                w = int(line.split("W=")[1].split()[0]) if "W=" in line else 1000
            else:
                f = line.split()
                if len(f) == 5 and f[0] in XLING_LANGS:
                    cells[(mode, w, f[0])] = float(f[3])
    return cells


def tab_xling():
    cells = parse_xling()
    lines = [HEADER,
             "\\begin{tabular}{lcccc}", "\\toprule",
             "held-out & tags & ranks & cats & catsrank \\\\", "\\midrule"]
    for lang in XLING_LANGS:
        vals = [cells[(m, 1000, lang)] for m in XLING_MODES]
        best = max(vals)
        row = " & ".join(f"\\textbf{{{v:.3f}}}" if v == best else f"{v:.3f}"
                         for v in vals)
        lines.append(f"{lang.capitalize()} & {row} \\\\")
    lines.append("\\midrule")
    for w in (1000, 500, 250):
        vals = [float(np.mean([cells[(m, w, l)] for l in XLING_LANGS]))
                for m in XLING_MODES]
        best = max(vals)
        row = " & ".join(f"\\textbf{{{v:.3f}}}" if v == best else f"{v:.3f}"
                         for v in vals)
        lines.append(f"mean, {w}-token windows & {row} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_xling.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("tab_xling.tex")


# --------------------------------------------------------------------------- #
# Table: LambdaG on the universal alphabet vs surface tokens
# (from the run_lambdag_catsrank.py score files)
# --------------------------------------------------------------------------- #

def tab_xalpha():
    from sklearn.metrics import roc_auc_score
    sys.path.insert(0, str(HERE.parent))
    from lambdag import cllr_min
    xs = HERE.parent / "scores"
    res = {}
    for fn in sorted(xs.glob("*__xalpha__L1000.jsonl")):
        ds, arm = fn.name.split("__")[:2]
        rows = [json.loads(l) for l in open(fn, encoding="utf-8")]
        y = np.array([r["within"] for r in rows])
        lam = np.array([r["lambda_G"] for r in rows])
        sq = np.array([r["sqrt"] for r in rows])
        res[(ds, arm)] = (float(roc_auc_score(y, lam)),
                          float(cllr_min(sq[y == 1], sq[y == 0])))
    lines = [HEADER,
             "\\begin{tabular}{lcccc}", "\\toprule",
             " & \\multicolumn{2}{c}{AUC ($\\lambda_G$)} & "
             "\\multicolumn{2}{c}{$C_{\\mathrm{llr}}^{\\min}$} \\\\",
             "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
             "dataset & surface & universal & surface & universal \\\\",
             "\\midrule"]
    for ds in ["german_novels", "english_novels", "hungarian_novels"]:
        a_s, c_s = res[(ds, "surface")]
        a_c, c_c = res[(ds, "catsrank")]
        lines.append(f"{pretty(ds)} & {a_s:.3f} & {a_c:.3f} & "
                     f"{c_s:.3f} & {c_c:.3f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_xalpha.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("tab_xalpha.tex")


# --------------------------------------------------------------------------- #
# Table: borrowed reference populations (from the run_xref.py score files)
# --------------------------------------------------------------------------- #

XREF_LANGS = ["german", "english", "french", "polish", "czech", "hungarian"]


def tab_xref():
    from sklearn.metrics import roc_auc_score
    sys.path.insert(0, str(HERE.parent))
    from lambdag import cllr_min
    xs = HERE.parent / "scores" / "xref"
    res = {}
    for fn in sorted(xs.glob("*__xref-*__L1000.jsonl")):
        ds, ref = fn.name.split("__")[0], fn.name.split("__")[1][5:]
        rows = [json.loads(l) for l in open(fn, encoding="utf-8")]
        y = np.array([r["within"] for r in rows])
        lam = np.array([r["lambda_G"] for r in rows])
        n = np.array([r["n_q"] for r in rows], dtype=float)
        t = np.array([np.mean(r["lam_j"]) / (np.std(r["lam_j"]) + 1e-9)
                      for r in rows])
        res[(ds.split("_")[0], ref.split("_")[0])] = {
            "auc": float(roc_auc_score(y, lam)),
            "auc_t": float(roc_auc_score(y, t)),
            "cmin_t": float(cllr_min(t[y == 1], t[y == 0])),
            "b": float(np.mean(lam[y == 0] / n[y == 0]))}
    lines = [HEADER,
             "\\begin{tabular}{lcccccc}", "\\toprule",
             " & \\multicolumn{3}{c}{AUC (symmetrised $\\lambda$)} & "
             "\\multicolumn{3}{c}{gauge $b_{\\mathrm{sym}}$} \\\\",
             "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}",
             "case & native & best donor & pooled & native & "
             "\\multicolumn{2}{c}{borrowed range} \\\\",
             "\\midrule"]
    for lang in XREF_LANGS:
        donors = {r: c for (d, r), c in res.items()
                  if d == lang and r not in ("native", "pooled")}
        best = max(donors, key=lambda r: donors[r]["auc"])
        bs = [c["b"] for c in donors.values()] + [res[(lang, "pooled")]["b"]]
        lines.append(
            f"{lang.capitalize()} & {res[(lang, 'native')]['auc']:.3f} & "
            f"{donors[best]['auc']:.3f} ({best[:2]}) & "
            f"{res[(lang, 'pooled')]['auc']:.3f} & "
            f"{res[(lang, 'native')]['b']:+.3f} & "
            f"{min(bs):+.3f} & {max(bs):+.3f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_xref.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("tab_xref.tex")


# --------------------------------------------------------------------------- #
# Table: cross-genre verification in German (from the run_xgenre.py files)
# --------------------------------------------------------------------------- #

XGENRE_DIRS = ["novels2dracor", "novels2poetree", "dracor2novels",
               "dracor2poetree", "poetree2novels", "poetree2dracor"]
GNAME = {"novels": "novels", "dracor": "drama", "poetree": "poetry"}


def tab_xgenre():
    from sklearn.metrics import roc_auc_score
    xs = HERE.parent / "scores" / "xgenre"
    res = {}
    for fn in sorted(xs.glob("*__L1000*.jsonl")):
        parts = fn.name.split("__")
        d, arm = parts[0], parts[1]
        kt = "10k" if "K10000" in parts[2] else "3k"
        rows = [json.loads(l) for l in open(fn, encoding="utf-8")]
        y = np.array([r["within"] for r in rows])
        lam = np.array([r["lambda_G"] for r in rows])
        n = np.array([r["n_q"] for r in rows], dtype=float)
        res[(d, arm, kt)] = {"auc": float(roc_auc_score(y, lam)),
                             "b": float(np.mean(lam[y == 0] / n[y == 0]))}
    lines = [HEADER,
             "\\begin{tabular}{lccccc}", "\\toprule",
             " & \\multicolumn{3}{c}{AUC (symmetrised $\\lambda$)} & "
             "\\multicolumn{2}{c}{gauge $b_{\\mathrm{sym}}$} \\\\",
             "\\cmidrule(lr){2-4}\\cmidrule(lr){5-6}",
             "known $\\to$ questioned & native & native, 10k known & "
             "foreign & native & foreign \\\\",
             "\\midrule"]
    for d in XGENRE_DIRS:
        g1, g2 = d.split("2")
        n3 = res[(d, "native", "3k")]
        n10 = res.get((d, "native", "10k"))
        f3 = res[(d, "foreign", "3k")]
        lines.append(f"{GNAME[g1]} $\\to$ {GNAME[g2]} & {n3['auc']:.3f} & "
                     + (f"{n10['auc']:.3f}" if n10 else "--")
                     + f" & {f3['auc']:.3f} & {n3['b']:+.3f} & "
                     f"{f3['b']:+.3f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_xgenre.tex").write_text("\n".join(lines) + "\n",
                                       encoding="utf-8")
    print("tab_xgenre.tex")


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    tab_b_measured()
    tab_withink()
    tab_decisive()
    tab_symmeter()
    tab_tempered()
    tab_routeb_real()
    fig_scatter()
    tab_engines()
    tab_hpy()
    tab_xling()
    tab_xalpha()
    tab_xref()
