# Regenerate the results tables of the CHR 2027 paper from experiments/*.log.
#
#   python experiments/make_paper_tables.py
#
# Writes LaTeX fragments to chr2027/ach-latex-template-v2/sections/tables/, which
# the paper \input{}s. Rerun after the KN grid advances; rows are append-only
# (a scored dataset never changes), only the coverage note is updated. No number
# in the paper is typed by hand -- every cell comes from a parsed log line.

import re
import sys
from collections import defaultdict
from pathlib import Path
from statistics import median

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUT = ROOT / "chr2027" / "ach-latex-template-v2" / "sections" / "tables"
OUT.mkdir(parents=True, exist_ok=True)

PAT = re.compile(
    r"^\s+(\S+)\s+kn\s+(\S+)\s+L=\s*(\S+)\s+AUC\s+([\d.]+)\s+Cllr\s+([\d.]+)"
    r"\s+sqrt\s+([\d.]+)\s+hapax\s+([\d.]+)")
GENRE = {"poetree": "Poetry", "dracor": "Drama", "novels": "Novels"}
LENGTHS = ["full", "1200", "600", "300", "150"]


def parse(log, seg_filter=None):
    """{(dataset, L): (auc, cllr, sqrt, hapax)} from one grid log."""
    rec = {}
    for line in open(log, encoding="utf-8"):
        m = PAT.match(line)
        if m and (seg_filter is None or m.group(2) == seg_filter):
            rec[(m.group(1), m.group(2), m.group(3))] = tuple(map(float, m.groups()[3:]))
    return rec


def split_name(ds):
    lang, corpus = ds.rsplit("_", 1)
    return lang.capitalize(), GENRE[corpus]


def complete(rec, ds, seg="sent"):
    return all((ds, seg, L) in rec for L in LENGTHS)


def fmt(x, nd=3):
    return f"{x:.{nd}f}"


def write_bankcal_lengths():
    """Sqrt vs bank-calibrated Cllr across the truncation grid, on the main-grid
    cases, from the pseudo-score files persisted by run_bankcal_short.py."""
    import json
    import numpy as np
    from sklearn.linear_model import LogisticRegression
    sys.path.insert(0, str(ROOT))
    from lambdag import cllr
    scores = HERE / "scores"
    DS = ["english_novels", "german_novels", "polish_novels", "ukrainian_novels",
          "lithuanian_novels", "english_dracor", "german_dracor",
          "english_poetree", "german_poetree"]
    LS = [1200, 600, 300, 150]

    def pair(ds, L):
        fp = scores / f"{ds}__kn__bankshort__L{L}.jsonl"
        fm = scores / f"{ds}__kn__sent__L{L}.jsonl"
        if not (fp.exists() and fm.exists()):
            return None
        rows = [json.loads(l) for l in open(fp, encoding="utf-8")]
        X = np.array([r["sqrt"] for r in rows]).reshape(-1, 1)
        y = np.array([int(r["known"] == r["quest"]) for r in rows])
        if len(set(y.tolist())) < 2:
            return None
        m = LogisticRegression(C=1e6).fit(X, y)
        prior = np.log(y.mean() / (1 - y.mean()))
        recs = [json.loads(l) for l in open(fm, encoding="utf-8")]
        s = np.array([r["sqrt"] for r in recs])
        yy = np.array([r["label"] for r in recs])
        llr = (m.coef_[0, 0] * s + m.intercept_[0] - prior) / np.log(10)
        return (float(cllr(s[yy == 1], s[yy == 0])),
                float(cllr(llr[yy == 1], llr[yy == 0])))

    rec = {(ds, L): pair(ds, L) for ds in DS for L in LS}
    if not any(rec.values()):
        return
    good = lambda v: (f"\\textbf{{{fmt(v)}}}" if v < 1 else fmt(v))
    lines = [
        "% AUTOGENERATED by experiments/make_paper_tables.py -- do not edit by hand",
        "\\begin{tabular}{l" + "rr" * len(LS) + "}", "\\toprule",
        " & " + " & ".join(f"\\multicolumn{{2}}{{c}}{{{L:,}}}".replace(",", "{,}")
                           for L in LS) + " \\\\",
        "Dataset & " + " & ".join(["sqrt & cal."] * len(LS)) + " \\\\",
        "\\midrule"]
    for ds in DS:
        if not any(rec[(ds, L)] for L in LS):
            continue
        lang, genre = split_name(ds)
        cells = []
        for L in LS:
            v = rec[(ds, L)]
            cells.append(f"{good(v[0])} & {good(v[1])}" if v else "--- & ---")
        lines.append(f"{lang} ({genre.lower()}) & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_bankcal_lengths.tex").write_text("\n".join(lines) + "\n",
                                                 encoding="utf-8")


def bankmain_cllr(ds):
    """Bank-calibrated full-length Cllr on the main-grid cases, or None.

    Reads the persisted pseudo-case scores written by run_bankcal_main.py and
    refits the (deterministic) logistic calibrator, so the table never depends
    on parsing a log line.
    """
    import json
    import numpy as np
    scores = HERE / "scores"
    fn = scores / f"{ds}__kn__bankmain__L0.jsonl"
    main = scores / f"{ds}__kn__sent__L0.jsonl"
    if not (fn.exists() and main.exists()):
        return None
    from sklearn.linear_model import LogisticRegression
    sys.path.insert(0, str(ROOT))
    from lambdag import cllr
    rows = [json.loads(l) for l in open(fn, encoding="utf-8")]
    if not rows:
        return None
    X = np.array([r["sqrt"] for r in rows]).reshape(-1, 1)
    y = np.array([int(r["known"] == r["quest"]) for r in rows])
    if len(set(y.tolist())) < 2:
        return None
    m = LogisticRegression(C=1e6).fit(X, y)
    prior = np.log(y.mean() / (1 - y.mean()))
    recs = [json.loads(l) for l in open(main, encoding="utf-8")]
    s = np.array([r["sqrt"] for r in recs])
    yy = np.array([r["label"] for r in recs])
    llr = (m.coef_[0, 0] * s + m.intercept_[0] - prior) / np.log(10)
    return float(cllr(llr[yy == 1], llr[yy == 0]))


def _cllrmin_full(ds):
    """Discrimination floor of the sqrt scores at full length, from score files."""
    import json
    import numpy as np
    sys.path.insert(0, str(ROOT))
    from lambdag import cllr_min
    fn = HERE / "scores" / f"{ds}__kn__sent__L0.jsonl"
    recs = [json.loads(l) for l in open(fn, encoding="utf-8")]
    s = np.array([r["sqrt"] for r in recs])
    y = np.array([r["label"] for r in recs])
    return float(cllr_min(s[y == 1], s[y == 0]))


def write_calibration(rec, datasets):
    """Full-length discrimination + the calibration-free renderings + the floor."""
    rows = defaultdict(list)
    for ds in datasets:
        a, c, s, h = rec[(ds, "sent", "full")]
        lang, genre = split_name(ds)
        rows[genre].append((lang, a, c, s, h, _cllrmin_full(ds)))
    lines = [
        "% AUTOGENERATED by experiments/make_paper_tables.py -- do not edit by hand",
        "\\begin{tabular}{lrrrrr}", "\\toprule",
        "Dataset & AUC & $C_{\\mathrm{llr}}$ ($\\lambda_G$) & "
        "$C_{\\mathrm{llr}}$ (sqrt) & $C_{\\mathrm{llr}}$ (hapax) & "
        "$C_{\\mathrm{llr}}^{\\min}$ \\\\",
        "\\midrule"]
    for genre in ["Novels", "Drama", "Poetry"]:
        if not rows[genre]:
            continue
        lines.append(f"\\multicolumn{{6}}{{l}}{{\\emph{{{genre}}}}} \\\\")
        for lang, a, c, s, h, m in sorted(rows[genre]):
            good = lambda v: (f"\\textbf{{{fmt(v)}}}" if v < 1 else fmt(v))
            lines.append(f"{lang} & {fmt(a)} & {fmt(c, 1)} & {good(s)} & {good(h)} "
                         f"& {fmt(m)} \\\\")
        lines.append("\\addlinespace")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_calibration.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_lengths(rec, datasets):
    """AUC under symmetric truncation, per dataset."""
    lines = [
        "% AUTOGENERATED by experiments/make_paper_tables.py -- do not edit by hand",
        "\\begin{tabular}{lrrrrr}", "\\toprule",
        "Dataset & full & 1{,}200 & 600 & 300 & 150 \\\\", "\\midrule"]
    grouped = defaultdict(list)
    for ds in datasets:
        lang, genre = split_name(ds)
        grouped[genre].append((lang, [rec[(ds, "sent", L)][0] for L in LENGTHS]))
    for genre in ["Novels", "Drama", "Poetry"]:
        if not grouped[genre]:
            continue
        lines.append(f"\\multicolumn{{6}}{{l}}{{\\emph{{{genre}}}}} \\\\")
        for lang, aucs in sorted(grouped[genre]):
            lines.append(lang + " & " + " & ".join(fmt(a) for a in aucs) + " \\\\")
        lines.append("\\addlinespace")
    med = [median(rec[(ds, "sent", L)][0] for ds in datasets) for L in LENGTHS]
    lines += ["\\midrule",
              "\\emph{median} & " + " & ".join(fmt(a) for a in med) + " \\\\",
              "\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_lengths.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_segmentation():
    """Sentences vs token windows, across evidence lengths. The main-text table
    carries {sent, w20} only (w10/w30 track w20 within a few thousandths); the
    full four-unit grid goes to the appendix."""
    seg_log = HERE / "segmentation.log"
    if not seg_log.exists():
        return
    rec = parse(seg_log)
    rec.update(parse(HERE / "primary.log", seg_filter="sent"))
    ds_all = sorted({d for d, s, L in rec if s in ("w10", "w20", "w30")})

    def emit(units, fname, spacer, subset=None):
        lines = [
            "% AUTOGENERATED by experiments/make_paper_tables.py -- do not edit by hand",
            "\\begin{tabular}{llrrrrr|rrr}", "\\toprule",
            " & & \\multicolumn{5}{c}{AUC} & "
            "\\multicolumn{3}{c}{$C_{\\mathrm{llr}}$ (sqrt)} \\\\",
            "Dataset & unit & full & 1{,}200 & 600 & 300 & 150 & full & 300 & 150 \\\\",
            "\\midrule"]
        for ds in ds_all:
            if subset and not ds.endswith(subset):
                continue
            lang, genre = split_name(ds)
            for i, seg in enumerate(units):
                name = f"{lang} ({genre.lower()})" if i == 0 else ""
                unit = "sent." if seg == "sent" else f"$w={seg[1:]}$"
                cells = []
                for L in LENGTHS:
                    v = rec.get((ds, seg, L))
                    cells.append(fmt(v[0]) if v else "---")
                for L in ["full", "300", "150"]:
                    v = rec.get((ds, seg, L))
                    cells.append(("\\textbf{" + fmt(v[2]) + "}" if v[2] < 1
                                  else fmt(v[2])) if v else "---")
                lines.append(f"{name} & {unit} & " + " & ".join(cells) + " \\\\")
            if spacer:
                lines.append("\\addlinespace")
        lines += ["\\bottomrule", "\\end{tabular}"]
        (OUT / fname).write_text("\n".join(lines) + "\n", encoding="utf-8")

    emit(["sent", "w20"], "tab_segmentation.tex", spacer=False)
    emit(["sent", "w10", "w20", "w30"], "tab_segmentation_full_drama.tex",
         spacer=True, subset="dracor")
    emit(["sent", "w10", "w20", "w30"], "tab_segmentation_full_poetry.tex",
         spacer=True, subset="poetree")


def write_longtexts():
    """Symmetric 1k/2k/5k control on five distant novel corpora (side experiment).

    Metrics are recomputed from the score files rather than parsed from the log,
    because the table also reports the Cllr = Cllr_min + loss decomposition at
    5,000 tokens, which the log lines do not carry.
    """
    import json
    import numpy as np
    from sklearn.metrics import roc_auc_score
    sys.path.insert(0, str(ROOT))
    from lambdag import cllr, cllr_min
    scores = HERE / "scores"

    def metrics(ds, L):
        fn = scores / f"{ds}__kn__long__L{L}.jsonl"
        if not fn.exists():
            return None
        recs = [json.loads(l) for l in open(fn, encoding="utf-8")]
        s = np.array([r["sqrt"] for r in recs])
        y = np.array([r["label"] for r in recs])
        return {"n": len(recs), "auc": float(roc_auc_score(y, s)),
                "cllr": float(cllr(s[y == 1], s[y == 0])),
                "cllrmin": float(cllr_min(s[y == 1], s[y == 0]))}

    def bankcal(ds):
        """Bank-calibrated Cllr on the SAME evaluation cases as the other columns.

        The pair matrix is calibration material only: per evaluation case, fit a
        logistic calibrator on the matrix pseudo-cases involving neither case
        author, then apply it to the case's own sqrt score. Comparable in-row with
        the uncalibrated sqrt column, which uses the identical case set.
        """
        fn = scores / f"{ds}__kn__bankcal__L5000.jsonl"
        if not fn.exists():
            return None
        from sklearn.linear_model import LogisticRegression
        from run_longtexts import build_cases
        from run_kn_grid import MASKED, read_tsv
        bank = {}
        for f in sorted((MASKED / ds / "bank").glob("*.tsv")):
            sents = read_tsv(f)
            bank[f.stem] = {"sents": sents, "ntok": sum(len(x) for x in sents)}
        cases = build_cases(bank, 5000)
        recs = [json.loads(l) for l in
                open(scores / f"{ds}__kn__long__L5000.jsonl", encoding="utf-8")]
        # recs are in exclusion-group order, NOT construction order -- join on the
        # stored case id, and verify the join against the labels before trusting it
        authors = [(cases[r["id"]][0], cases[r["id"]][1]) for r in recs]
        assert all(int(a == b) == r["label"] for (a, b), r in zip(authors, recs)), \
            f"{ds}: case-id join does not reproduce the labels"
        s = np.array([r["sqrt"] for r in recs])
        y = np.array([r["label"] for r in recs])
        mat = [json.loads(l) for l in open(fn, encoding="utf-8")]
        ms = np.array([m["sqrt"] for m in mat])
        my = np.array([int(m["known"] == m["quest"]) for m in mat])
        mk = [m["known"] for m in mat]; mq = [m["quest"] for m in mat]
        llr = np.empty(len(s))
        for i, (a, b) in enumerate(authors):
            tr = [j for j in range(len(mat)) if {mk[j], mq[j]}.isdisjoint({a, b})]
            m = LogisticRegression(C=1e6).fit(ms[tr].reshape(-1, 1), my[tr])
            prior = np.log(my[tr].mean() / (1 - my[tr].mean()))
            llr[i] = (m.coef_[0, 0] * s[i] + m.intercept_[0] - prior) / np.log(10)
        return {"cal": float(cllr(llr[y == 1], llr[y == 0]))}

    rec = {}
    for ds in ["english_novels", "german_novels", "polish_novels",
               "ukrainian_novels", "lithuanian_novels"]:
        ms = {L: metrics(ds, L) for L in [1000, 2000, 5000]}
        if all(ms.values()):
            rec[ds] = ms
    if not rec:
        return
    good = lambda v: (f"\\textbf{{{fmt(v)}}}" if v < 1 else fmt(v))
    lines = [
        "% AUTOGENERATED by experiments/make_paper_tables.py -- do not edit by hand",
        "\\begin{tabular}{lrrrrrrr|rrr}", "\\toprule",
        " & & \\multicolumn{3}{c}{AUC} & "
        "\\multicolumn{3}{c}{$C_{\\mathrm{llr}}$ (sqrt)} & "
        "\\multicolumn{3}{c}{at 5{,}000} \\\\",
        "Dataset & $n$ & 1{,}000 & 2{,}000 & 5{,}000 & 1{,}000 & 2{,}000 & 5{,}000 "
        "& $C_{\\mathrm{llr}}^{\\min}$ & loss & bank cal. \\\\",
        "\\midrule"]
    for ds, ms in rec.items():
        lang, _ = split_name(ds)
        aucs = " & ".join(fmt(ms[L]["auc"]) for L in [1000, 2000, 5000])
        sqrts = " & ".join(good(ms[L]["cllr"]) for L in [1000, 2000, 5000])
        m5 = ms[5000]
        bc = bankcal(ds)
        tail = f"\\textbf{{{fmt(bc['cal'])}}}" if bc else "---"
        lines.append(f"{lang} & {ms[5000]['n']} & {aucs} & {sqrts} & "
                     f"{fmt(m5['cllrmin'])} & {fmt(m5['cllr'] - m5['cllrmin'])} & "
                     f"{tail} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (OUT / "tab_longtexts.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    rec = parse(HERE / "primary.log")
    datasets = sorted({d for d, s, L in rec if s == "sent" and complete(rec, d)})
    write_calibration(rec, datasets)
    write_lengths(rec, datasets)
    write_segmentation()
    write_longtexts()
    write_bankcal_lengths()
    n_sqrt = sum(1 for d in datasets if rec[(d, "sent", "full")][2] < 1)
    n_hap = sum(1 for d in datasets if rec[(d, "sent", "full")][3] < 1)
    med_auc = median(rec[(d, "sent", "full")][0] for d in datasets)
    (OUT / "coverage.tex").write_text(  # \input-able note + macros for the prose
        "% AUTOGENERATED by experiments/make_paper_tables.py -- do not edit by hand\n"
        f"\\newcommand{{\\nDatasetsScored}}{{{len(datasets)}}}\n"
        f"\\newcommand{{\\medianAUCfull}}{{{med_auc:.3f}}}\n"
        f"\\newcommand{{\\nSqrtGood}}{{{n_sqrt}}}\n"
        f"\\newcommand{{\\nHapaxGood}}{{{n_hap}}}\n", encoding="utf-8")
    print(f"{len(datasets)} datasets complete -> {OUT}")
    print(f"   median AUC {med_auc:.3f}; sqrt<1 in {n_sqrt}, hapax<1 in {n_hap}")


if __name__ == "__main__":
    main()
