# Every number in the article comes from here, and none is typed into the prose.
#
# The script reads the result files the experiments wrote, prints the digest a
# chapter quotes, and regenerates the tables that chapter inputs. Run it before
# reading a draft: if a number in the text and a number here disagree, the text
# is wrong.
#
#   python tools/make_tables.py
#
# Reads   medieval/kc_reuse/*.json, medieval/kc_reuse/konrad_summary.tsv,
#         medieval/kc_reuse/kc_regions_verdicts.tsv,
#         medieval/rhyme_mfw.tsv, medieval/rhyme_mfw_authors.tsv,
#         scores/vorau_rolling/*.jsonl
# Writes  tables/tab_rolling.tex, tables/tab_verdicts.tex, tables/tab_rhyme.tex

import csv
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
PAPER = HERE.parent
ROOT = PAPER.parent.parent
REUSE = ROOT / "medieval" / "kc_reuse"
ROLL = ROOT / "scores" / "vorau_rolling"
NL = "\n"
EOL = " \\\\"


def runs(units, gap=1):
    """the contiguous stretches a list of unit indices falls into"""
    out, cur = [], []
    for u in sorted(units):
        if cur and u - cur[-1] > gap:
            out.append(cur)
            cur = []
        cur.append(u)
    if cur:
        out.append(cur)
    return out


def reuse_digest():
    print("REUSE MASK (chapter 7.1)")
    tot = []
    for f in sorted(REUSE.glob("kcd__*.json")):
        d = json.load(open(f, encoding="utf-8"))
        r = runs(d["masked_units"])
        tot.append((d["witness"].split("__")[-1], d["tokens"], d["k"],
                    d["masked_tokens"], d["masked_share"],
                    max(len(x) for x in r) if r else 0, len(r),
                    sorted(d["partners"],
                           key=lambda p: -d["partners"][p]["z"])[:3]))
    for w, n, k, mt, ms, lr, nr, pa in tot:
        print(f"  witness {w:4} {n:7,} tokens, k={k}: {mt:5,} masked "
              f"({ms:.1%}), {nr:3} stretches, longest {lr:2} units; "
              f"partners {', '.join(p.split('__')[-1] for p in pa)}")
    print(f"  -> {len(tot)} witnesses; masked share "
          f"{min(x[4] for x in tot):.1%}-{max(x[4] for x in tot):.1%}, "
          f"longest single stretch {max(x[5] for x in tot)} units")
    print()


def vorau_digest():
    print("VORAU COD. 276 (chapter 7.2)")
    for L in (1000, 2000):
        rows = [json.loads(l) for l in
                (ROLL / f"lemma__L{L}__w100__edition.jsonl").open(
                    encoding="utf-8")]
        meta = rows[0]
        win = [r for r in rows if r["kind"] == "window"]
        for r in win:
            r["lambda_G"] = float(r["lambda_G"])
            r["start"] = int(r["start"])
        ch = [r for r in win if r["text"] == "kaiserchronik"]
        al = [r for r in win if r["text"] == "alexanderlied"]
        y = np.array([r["lambda_G"] for r in ch])
        med = float(np.median(y))
        sd = 1.4826 * float(np.median(np.abs(y - med))) or 1.0
        auc = float(np.mean([(a["lambda_G"] < c["lambda_G"])
                             + 0.5 * (a["lambda_G"] == c["lambda_G"])
                             for c in ch for a in al]))
        drop = (med - float(np.median([r["lambda_G"] for r in al]))) / sd
        inside = [r["start"] for r in win if r["lambda_G"] > med - 3 * sd]
        below = [r["start"] for r in win if r["lambda_G"] <= med - 3 * sd]
        gap = (min(below) - max(x for x in inside if x < min(below))
               if below and inside else float("nan"))
        print(f"  L={L}: {len(ch)} chronicle windows {med:,.0f} +- {sd:,.0f}, "
              f"{len(al)} Alexanderlied windows {drop:.1f} robust standard "
              f"deviations below, AUC {auc:.3f}; step {meta['step']} tokens, "
              f"fall located within {gap:.0f} tokens; "
              f"{len(meta['known_from'])} known passages, "
              f"{len(meta['donors'])} donors")
    print()


def candidates():
    print("CANDIDATES ON THE OLDEST WITNESS (chapter 7.3)")
    with (REUSE / "konrad_summary.tsv").open(encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh, delimiter="\t"))
    for r in rows:
        print(f"  {r['run']:46} chronicle windows z={r['chronicle_windows_z']}"
              f", best {r['best_window_z']}, ceiling {r['ceiling_z']}, "
              f"share above cohort {r['share_above_whole_cohort']}")
    keep = [r for r in rows if "shared wording" not in r["run"]]
    body = NL.join(
        f"{r['run'].replace('known: ', '')} & {r['known'].split('__')[-1]} & "
        f"{r['chronicle_windows_z']} & {r['best_window_z']} & "
        f"{r['ceiling_z']} & {float(r['share_above_whole_cohort']):.2f}" + EOL
        for r in keep)
    tex = (r"""% Regenerated by tools/make_tables.py; nothing typed in by hand.
\begin{table}[t]
\centering
\caption{The candidates on the oldest witness of the \emph{Kaiserchronik}.
  Each candidate supplies the known passages; the chronicle's windows are
  scored against them and against a cohort of passages by other authors. The
  deviation is in that cohort's own robust standard deviations, and the ceiling
  is the deviation reached by a further witness of the candidate's own work.}
\label{tab:rolling}
\begin{tabular}{llrrrr}
\toprule
candidate & known text & windows & best window & ceiling & share above
cohort \\
\midrule
""" + body + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    (PAPER / "tables" / "tab_rolling.tex").write_text(tex, encoding="utf-8")
    print(f"  wrote tables/tab_rolling.tex ({len(keep)} rows)")
    print()


def verdicts():
    print("A VERDICT FOR EACH FRAGMENT (chapter 7.4)")
    with (REUSE / "kc_regions_verdicts.tsv").open(encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh, delimiter="\t"))
    with (REUSE / "kc_regions_crosswork.tsv").open(encoding="utf-8") as fh:
        xw = {r["region"]: r for r in csv.DictReader(fh, delimiter="\t")}
    yes = [r for r in rows if r["verdict"] == "SAME"]
    strong = [r for r in yes if float(r["llr"]) >= 1.0]
    ctrl = [r for r in rows if r["verdict_control"] == "SAME"]
    print("  calibrated on the chronicle's own other regions (the same WORK):")
    print(f"    the candidate called same author in {len(yes)} of {len(rows)}, "
          f"{len(strong)} of them at ten to one or better, strongest "
          f"{max(10 ** float(r['llr']) for r in rows):,.0f} to one; a different "
          f"author of the same milieu in {len(ctrl)}")
    a = next(iter(xw.values()))
    print("  calibrated on one author's two DIFFERENT works:")
    print(f"    the verifier on that class: AUC {float(a['auc_class']):.3f}, "
          f"Cllr {float(a['cllr_class']):.3f}, and the odds it supports reach "
          f"at most {10 ** float(a['elub_hi']):.0f} to one")
    n_c = sum(float(r["llr"]) > 0 for r in xw.values())
    n_t = sum(float(r["llr_control"]) > 0 for r in xw.values())
    n_ab = sum(float(r["z"]) > float(r["z_control"]) for r in xw.values())
    print(f"    positive odds for the candidate in {n_c} of {len(xw)} regions, "
          f"for the control in {n_t}; the candidate stands above the control in "
          f"{n_ab}")
    body = NL.join(
        f"{r['verses'].replace('-', '--')} & {float(r['q']):.3f} & "
        f"{float(xw[r['region']]['z']):.1f} & {float(r['llr']):+.2f} & "
        f"{float(xw[r['region']]['llr']):+.2f} & "
        f"{float(xw[r['region']]['z_control']):.1f} & "
        f"{float(r['llr_control']):+.2f} & "
        f"{float(xw[r['region']]['llr_control']):+.2f}" + EOL
        for r in rows)
    tex = (r"""% Regenerated by tools/make_tables.py; nothing typed in by hand.
\begin{table}[t]
\centering\small
\caption{A verdict for each fragment of the oldest witness. Every region of the
  chronicle is made the known text in turn, and the candidate and a different
  author of the same milieu are scored against it; $q$ is the tail probability
  against the cohort of strangers, corrected to hold the rate of false verdicts
  over all twenty regions at five per cent, and $z$ is the deviation from that
  cohort in its own robust spread. The two likelihood ratios differ only in the
  class they were calibrated on: the chronicle's own other regions, which are
  the same work, and one author's two different works, which is what the
  attribution asks about.}
\label{tab:verdicts}
\begin{tabular}{lrrrrrrr}
\toprule
& & \multicolumn{3}{c}{the candidate} & \multicolumn{3}{c}{a different author}
\\
\cmidrule(lr){3-5}\cmidrule(lr){6-8}
verses & $q$ & $z$ & LR same work & LR two works & $z$ & LR same work &
LR two works \\
\midrule
""" + body + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    (PAPER / "tables" / "tab_verdicts.tex").write_text(tex, encoding="utf-8")
    print("  wrote tables/tab_verdicts.tex")
    print()


LAB = {("surface_full", "all"): "the scribe's form, every position",
       ("surface_full", "rhyme"): "the scribe's form, the rhyme only",
       ("surface_full", "rime"): "the scribe's form, the rime only",
       ("lemma_full", "all"): "the canonical lemma, every position",
       ("lemma_full", "rhyme"): "the canonical lemma, the rhyme only"}


def rhyme_baseline():
    print("THE RHYME-WORD BASELINE (chapter 5)")
    with (ROOT / "medieval" / "rhyme_mfw.tsv").open(encoding="utf-8") as fh:
        rows = [r for r in csv.DictReader(fh, delimiter="\t")
                if r["top"] == "100" and r["n_identities"] == "1"]
    for r in rows:
        print(f"  witnesses, {LAB[(r['stream'], r['positions'])]:38} "
              f"floor {float(r['scribe_floor']):.3f}, "
              f"AUC {float(r['auc']):.3f} +- {float(r['auc_sd']):.3f} "
              f"({r['n_same_pairs']} pairs, {r['n_identities']} identity)")
    with (ROOT / "medieval" / "rhyme_mfw_authors.tsv").open(
            encoding="utf-8") as fh:
        ar = [r for r in csv.DictReader(fh, delimiter="\t")
              if r["top"] == "200" and r["verses"] == "2000"]
    for r in ar:
        print(f"  editions, {LAB[(r['stream'], r['positions'])]:38} "
              f"AUC {float(r['auc']):.3f} +- {float(r['auc_sd']):.3f} "
              f"({r['n_same_pairs']} cross-work pairs, "
              f"{r['n_identities']} identities)")
    body = NL.join(f"{LAB[(r['stream'], r['positions'])]} & "
                   f"{float(r['scribe_floor']):.3f} & "
                   f"{float(r['auc']):.3f}" + EOL for r in rows)
    body2 = NL.join(f"{LAB[(r['stream'], r['positions'])]} & & "
                    f"{float(r['auc']):.3f}" + EOL for r in ar)
    n_w = rows[0]["n_same_pairs"] if rows else "0"
    n_a = ar[0]["n_same_pairs"] if ar else "0"
    tex = (r"""% Regenerated by tools/make_tables.py; nothing typed in by hand.
\begin{table}[t]
\centering
\caption{The rhyme-word baseline, in the design the philological stylometry of
  Middle High German verse has used: frequency profiles over the hundred most
  frequent words of each feature set, compared by Burrows's delta. Above, on the
  witnesses of this corpus, where the floor is the mean distance between two
  witnesses of one work and the area under the curve separates works of one
  author from works of different authors ("""
           + n_w + r""" same-author pairs). Below, on
  normalised editions, where a same-author pair is required to cross a work and
  the profile is taken over the two hundred most frequent features ("""
           + n_a + r""" such
  pairs, 17 authors).}
\label{tab:rhyme}
\begin{tabular}{lrr}
\toprule
feature set & floor between witnesses & AUC \\
\midrule
""" + body + r"""
\midrule
\multicolumn{3}{l}{\emph{editions, every pair crossing a work}} \\
""" + body2 + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    (PAPER / "tables" / "tab_rhyme.tex").write_text(tex, encoding="utf-8")
    print("  wrote tables/tab_rhyme.tex")
    print()


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    reuse_digest()
    vorau_digest()
    candidates()
    verdicts()
    rhyme_baseline()


if __name__ == "__main__":
    main()
